### PR TITLE
Fix `net_certificate` table to return zero rows if domains does not have a certificate. Closes #41

### LINKED ISSUE #41: net_certificate crashes when the domain does not have an SSL certificate
**Describe the bug**
I am running `net_certificate` to identify domains with SSL issues.  If a domain does not have an SSL certificate, the plugin simply fails, and does not process anything.

```
Warning: executeQueries: query 1 of 1 failed: ERROR: rpc error: code = Unknown desc = TLS connection failed: dial tcp 164.92.154.37:443: i/o timeout (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
`steampipe version 0.15.3`

**Plugin version (`steampipe plugin list`)**
`| hub.steampipe.io/plugins/turbot/net@latest         | 0.6.0   | net         |`

**To reproduce**
```
with domains as (
    SELECT 'steampipe.io' as domain
    UNION ALL SELECT 'massyn.com' as domain
)

SELECT
    N.domain,
    N.revoked
FROM
  net_certificate N
where
  N.domain IN (SELECT * FROM domains)
```

**Expected behavior**
In this example, I would expect the domain `massyn.com` to come up with a `null` value, instead of failing the script with the error message.

**Additional context**
None

### PR DESCRIPTION
**Pull request by Subhajit97**
# Example query results
<details>
  <summary>Results</summary>

```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

File: net/table_net_certificate.go [hunk 1]
```diff
@@ -142,16 +143,27 @@ func tableNetCertificateList(ctx context.Context, d *plugin.QueryData, h *plugin
...
+		Control: func(network, address string, c syscall.RawConn) error { // This gets called once the TCP connection gets opened before handshake
+			tcpConnectionCreated = true
+			return nil
+		},
 	}
 
 	conn, err := tls.DialWithDialer(dialer, "tcp", addr, &cfg)
 	if err != nil {
+		if tcpConnectionCreated {
+			plugin.Logger(ctx).Error("net_certificate.tableNetCertificateList", "failed to perform TLS handshake: ", err)
```
Comment (cbruno10) [inline net/table_net_certificate.go:159]:
```suggestion
			plugin.Logger(ctx).Error("net_certificate.tableNetCertificateList", "failed to perform TLS handshake:", err)
```

do we need the extra space, or does the plugin logger handle this?

File: net/table_net_certificate.go [hunk 2]
```diff
@@ -142,16 +143,27 @@ func tableNetCertificateList(ctx context.Context, d *plugin.QueryData, h *plugin
...
+			return nil, nil
+		}
 		plugin.Logger(ctx).Error("net_certificate.tableNetCertificateList", "TLS connection failed: ", err)
 		return nil, errors.New("TLS connection failed: " + err.Error())
 	}
+	defer conn.Close()
```
Comment (cbruno10) [inline net/table_net_certificate.go:165]: What happens if we hit an err, do we still attempt to defer connection closing? Should this be before we check for the err?

**Review by cbruno10 — CHANGES_REQUESTED** [review]
please see comments, thanks!

**Review by cbruno10 — APPROVED** [review]
